#pragma once

#include <cstdint>
#include <filesystem>
#include <limits>
#include <string>
#include <vector>

#include "benders/CvarTailScoreDiagnostics.hpp"
#include "solver/ModelResult.hpp"

namespace firebreak::io {

struct RestrictedCandidateRoundResult {
    int round_index = 0;
    std::string stage_type;
    std::string risk_measure = "expected";
    int active_candidate_count = 0;
    double active_candidate_fraction = 0.0;
    std::string activation_policy;
    std::vector<int> newly_activated_candidates;
    std::string solve_status;
    double objective = std::numeric_limits<double>::quiet_NaN();
    double best_bound = std::numeric_limits<double>::quiet_NaN();
    double mip_gap = std::numeric_limits<double>::quiet_NaN();
    double runtime_seconds = 0.0;
    double time_limit_seconds = 0.0;
    double remaining_global_time_before_stage = std::numeric_limits<double>::quiet_NaN();
    double remaining_global_time_after_stage = std::numeric_limits<double>::quiet_NaN();
    int cuts_added = 0;
    int candidate_incumbents_checked = 0;
    int subproblem_solves = 0;
    double callback_time_seconds = 0.0;
    double subproblem_time_seconds = 0.0;
    int cut_pool_size_before_stage = 0;
    int cuts_reused_at_stage = 0;
    int new_cuts_added_to_pool = 0;
    int duplicate_cuts_skipped = 0;
    double max_cut_violation = 0.0;
    std::vector<int> selected_firebreaks;
    int active_count_before_maintenance = 0;
    int active_count_after_activation = 0;
    int active_count_after_deactivation = 0;
    std::vector<int> deactivated_candidates;
    int protected_selected_count = 0;
    int protected_min_age_count = 0;
    int protected_cooldown_count = 0;
    int protected_newly_activated_count = 0;
    int protected_tail_count = 0;
    int deactivation_candidate_count = 0;
    int reactivation_blocked_by_cooldown_count = 0;
    int oscillation_event_count = 0;
    std::vector<int> selected_candidates_protected;
    std::vector<int> tail_protected_candidates;
    std::string candidate_score_mode = "generic";
    double candidate_tail_score_gamma = 0.5;
    int candidate_tail_protection_size = 0;
    std::vector<std::pair<int, double>> top_blend_candidates;
    std::vector<std::pair<int, double>> top_generic_candidates_for_score_mode;
    std::vector<std::pair<int, double>> top_tail_candidates;
    int top_blend_tail_overlap = 0;
    int top_blend_generic_overlap = 0;
    int activated_tail_top_k_overlap = 0;
    int deactivated_tail_top_k_warning_count = 0;
};

struct StandardExperimentResult {
    std::string experiment_id;
    int case_id = -1;
    std::string run_id;
    std::string timestamp;
    std::string landscape;
    std::string method;
    std::string objective_metric;
    double alpha = 0.0;
    int budget = 0;
    int train_scenario_count = 0;
    int test_scenario_count = 0;
    std::vector<int> train_ids;
    std::vector<int> test_ids;
    std::string solver_status;
    double objective_in_sample = 0.0;
    double best_bound = 0.0;
    double mip_gap = 0.0;
    double runtime_seconds = 0.0;
    int solver_status_code = 0;
    long long explored_nodes = -1;
    std::size_t num_variables = 0;
    std::size_t num_constraints = 0;
    int solver_iterations = 0;
    int cuts_added = 0;
    double max_cut_violation = 0.0;
    std::string benders_status;
    int benders_iterations = 0;
    int benders_cuts_added = 0;
    double benders_final_max_cut_violation = 0.0;
    double benders_largest_intermediate_cut_violation = 0.0;
    std::string benders_termination_reason;
    double benders_master_solve_time_sec = 0.0;
    double benders_subproblem_time_sec = 0.0;
    int benders_subproblems_solved = 0;
    double benders_average_subproblem_time_sec = 0.0;
    double benders_max_subproblem_time_sec = 0.0;
    bool benders_use_lifted_lower_bounds = false;
    int benders_lifted_lower_bound_count = 0;
    double benders_lifted_lower_bound_precompute_time_sec = 0.0;
    int benders_lifted_lower_bound_nonzero_coefficients = 0;
    double benders_lifted_lower_bound_min_rhs = std::numeric_limits<double>::quiet_NaN();
    double benders_lifted_lower_bound_max_rhs = std::numeric_limits<double>::quiet_NaN();
    bool benders_lifted_lower_bound_weighted = false;
    std::string benders_lifted_lower_bound_weight_map_hash;
    int benders_lifted_lower_bound_scenarios_precomputed = 0;
    int benders_lifted_lower_bound_singletons_evaluated = 0;
    double benders_lifted_lower_bound_no_firebreak_loss_min =
        std::numeric_limits<double>::quiet_NaN();
    double benders_lifted_lower_bound_no_firebreak_loss_max =
        std::numeric_limits<double>::quiet_NaN();
    double benders_lifted_lower_bound_singleton_benefit_min =
        std::numeric_limits<double>::quiet_NaN();
    double benders_lifted_lower_bound_singleton_benefit_max =
        std::numeric_limits<double>::quiet_NaN();
    int benders_lifted_lower_bound_constraints_added = 0;
    bool benders_lifted_lower_bound_cache_hit = false;
    std::string benders_lifted_lower_bound_validity_mode;
    std::vector<std::string> benders_lifted_lower_bound_notes;
    std::vector<solver::BendersIterationLog> benders_iteration_log;
    bool branch_benders_enabled = false;
    int branch_benders_callback_calls = 0;
    int branch_benders_candidate_callback_calls = 0;
    int branch_benders_incumbent_callback_calls = 0;
    int branch_benders_candidate_incumbents_checked = 0;
    int branch_benders_subproblems_attempted = 0;
    int branch_benders_subproblems_solved = 0;
    int branch_benders_lazy_cuts_added = 0;
    double branch_benders_max_cut_violation = 0.0;
    double branch_benders_largest_incumbent_cut_violation = 0.0;
    double branch_benders_callback_time_sec = 0.0;
    double branch_benders_subproblem_time_sec = 0.0;
    double branch_benders_average_subproblem_time_sec = 0.0;
    double branch_benders_max_subproblem_time_sec = 0.0;
    double branch_benders_cut_construction_time_sec = 0.0;
    double branch_benders_lazy_cut_insertion_time_sec = 0.0;
    int branch_benders_violated_cuts = 0;
    int branch_benders_nonviolated_cuts = 0;
    int branch_benders_skipped_cuts = 0;
    int branch_benders_duplicate_cuts = 0;
    std::vector<solver::BranchBendersIncumbentLog> branch_benders_incumbent_log;
    bool combinatorial_benders_enabled = false;
    std::string combinatorial_benders_lift_mode = "heuristic";
    std::string combinatorial_benders_scenario_order = "eta-asc";
    double combinatorial_benders_cut_sampling_ratio = 0.10;
    bool combinatorial_benders_fractional_separation_enabled = true;
    bool combinatorial_benders_initial_cuts_enabled = true;
    int combinatorial_benders_integer_cuts_added = 0;
    int combinatorial_benders_fractional_cuts_added = 0;
    int combinatorial_benders_initial_cuts_added = 0;
    int combinatorial_benders_scenarios_checked = 0;
    double combinatorial_benders_separation_time_sec = 0.0;
    double combinatorial_benders_avg_paths_per_cut = 0.0;
    double combinatorial_benders_avg_cut_nonzeros = 0.0;
    int combinatorial_benders_num_violated_cuts = 0;
    bool combinatorial_benders_weighted = false;
    std::string combinatorial_benders_mode;
    std::string combinatorial_benders_weight_map_hash;
    int combinatorial_benders_weighted_recourse_evaluations = 0;
    int combinatorial_benders_duplicate_cuts = 0;
    int combinatorial_benders_cuts_tight_at_incumbent = 0;
    bool combinatorial_benders_lifting_enabled = false;
    bool combinatorial_benders_scenario_sampling_enabled = false;
    double combinatorial_benders_max_tightness_error = 0.0;
    double combinatorial_benders_max_violation = 0.0;
    double combinatorial_benders_propagation_time_sec = 0.0;
    double combinatorial_benders_cut_build_time_sec = 0.0;
    std::string combinatorial_benders_validity_mode;
    bool combinatorial_weighted = false;
    std::string combinatorial_mode;
    std::string combinatorial_weight_map_hash;
    std::string combinatorial_scenario_order = "eta-asc";
    double combinatorial_cut_sampling_ratio = 0.10;
    int combinatorial_candidate_callbacks = 0;
    int combinatorial_scenarios_evaluated = 0;
    int combinatorial_weighted_recourse_evaluations = 0;
    int combinatorial_cuts_generated = 0;
    int combinatorial_cuts_added = 0;
    int combinatorial_duplicate_cuts = 0;
    int combinatorial_cuts_tight_at_incumbent = 0;
    double combinatorial_max_tightness_error = 0.0;
    double combinatorial_max_violation = 0.0;
    double combinatorial_propagation_time_sec = 0.0;
    double combinatorial_cut_build_time_sec = 0.0;
    double combinatorial_callback_time_sec = 0.0;
    std::string combinatorial_validity_mode;
    bool combinatorial_lifting_enabled = false;
    bool combinatorial_fractional_cuts_enabled = false;
    bool combinatorial_initial_cuts_enabled = false;
    bool combinatorial_scenario_sampling_enabled = false;
    bool combinatorial_lifting_weighted = false;
    std::string combinatorial_lifting_mode;
    std::string combinatorial_lifting_weight_map_hash;
    int combinatorial_lifting_attempts = 0;
    int combinatorial_lifting_successes = 0;
    int combinatorial_lifting_failures = 0;
    int combinatorial_candidates_considered_for_lifting = 0;
    int combinatorial_coefficients_changed = 0;
    int combinatorial_propagation_evaluations_for_lifting = 0;
    int combinatorial_baseline_cut_nonzeros = 0;
    int combinatorial_lifted_cut_nonzeros = 0;
    double combinatorial_max_coefficient_change = 0.0;
    double combinatorial_max_baseline_tightness_error = 0.0;
    double combinatorial_max_lifted_tightness_error = 0.0;
    int combinatorial_lifted_cuts_dominating_baseline = 0;
    double combinatorial_lifting_time_sec = 0.0;
    std::string combinatorial_lifting_validity_mode;
    int combinatorial_initial_solutions_evaluated = 0;
    int combinatorial_initial_cuts_generated = 0;
    int combinatorial_initial_duplicate_cuts = 0;
    double combinatorial_initial_cut_time_sec = 0.0;
    bool combinatorial_root_cuts_enabled = false;
    int combinatorial_root_rounds = 0;
    int combinatorial_root_integer_points_evaluated = 0;
    int combinatorial_root_fractional_points_evaluated = 0;
    int combinatorial_root_cuts_generated = 0;
    int combinatorial_root_cuts_added = 0;
    int combinatorial_root_duplicate_cuts = 0;
    double combinatorial_root_cut_time_sec = 0.0;
    std::string combinatorial_root_skipped_reason;
    std::string combinatorial_fractional_validity_mode;
    int combinatorial_fractional_separation_calls = 0;
    int combinatorial_fractional_scenarios_evaluated = 0;
    int combinatorial_fractional_cuts_generated = 0;
    int combinatorial_fractional_duplicate_cuts = 0;
    double combinatorial_fractional_max_violation = 0.0;
    double combinatorial_fractional_max_tightness_error = 0.0;
    double combinatorial_fractional_separation_time_sec = 0.0;
    int combinatorial_realized_sample_size = 0;
    bool combinatorial_sampling_exact_fallback = false;
    bool combinatorial_scenario_policy_exact = true;
    bool combinatorial_scenario_policy_heuristic = false;
    bool combinatorial_full_verification_before_acceptance = true;
    int combinatorial_candidate_initial_sample_scenarios_evaluated = 0;
    int combinatorial_candidate_fallback_scenarios_evaluated = 0;
    int combinatorial_candidate_full_sweeps = 0;
    int combinatorial_candidates_rejected_in_initial_sample = 0;
    int combinatorial_candidates_rejected_in_fallback = 0;
    int combinatorial_candidates_fully_verified = 0;
    int combinatorial_sampled_violations = 0;
    int combinatorial_fallback_violations = 0;
    int combinatorial_scenarios_skipped_after_candidate_rejection = 0;
    double combinatorial_sampling_time_sec = 0.0;
    double combinatorial_ordering_time_sec = 0.0;
    bool coverage_llbi_enabled = false;
    int coverage_llbi_num_zeta_vars = 0;
    int coverage_llbi_num_constraints = 0;
    double coverage_llbi_precompute_time_sec = 0.0;
    bool coverage_llbi_weighted = false;
    std::string coverage_llbi_weight_map_hash;
    int coverage_llbi_scenarios_precomputed = 0;
    int coverage_llbi_baseline_cells = 0;
    int coverage_llbi_auxiliary_variables = 0;
    int coverage_llbi_linking_constraints = 0;
    int coverage_llbi_loss_constraints = 0;
    int coverage_llbi_nonempty_coverage_sets = 0;
    int coverage_llbi_total_incidence_terms = 0;
    double coverage_llbi_build_time_sec = 0.0;
    std::string coverage_llbi_validity_mode;
    bool path_llbi_enabled = false;
    int path_llbi_num_b_vars = 0;
    int path_llbi_num_path_constraints = 0;
    int path_llbi_num_paths_used = 0;
    bool path_llbi_weighted = false;
    std::string path_llbi_weight_map_hash;
    int path_llbi_scenarios_precomputed = 0;
    int path_llbi_baseline_nodes = 0;
    int path_llbi_auxiliary_variables = 0;
    int path_llbi_path_constraints = 0;
    int path_llbi_loss_constraints = 0;
    int path_llbi_total_paths = 0;
    int path_llbi_total_candidate_incidence_terms = 0;
    int path_llbi_nodes_without_paths = 0;
    bool path_llbi_path_enumeration_complete = true;
    int path_llbi_paths_truncated = 0;
    double path_llbi_precompute_time_sec = 0.0;
    double path_llbi_build_time_sec = 0.0;
    std::string path_llbi_validity_mode;
    bool projected_coverage_llbi_enabled = false;
    bool projected_path_llbi_enabled = false;
    std::string projected_llbi_family;
    std::string projected_llbi_strategy;
    std::string projected_llbi_mode;
    int projected_llbi_root_rounds = 0;
    int projected_llbi_cuts_added = 0;
    int projected_llbi_coverage_cuts_added = 0;
    int projected_llbi_path_cuts_added = 0;
    int projected_llbi_violated_cuts_found = 0;
    double projected_llbi_separation_time_sec = 0.0;
    double projected_llbi_solve_time_sec = 0.0;
    double projected_llbi_total_time_sec = 0.0;
    int projected_llbi_total_nonzeros = 0;
    double projected_llbi_avg_nonzeros_per_cut = 0.0;
    int projected_llbi_max_nonzeros_per_cut = 0;
    double projected_llbi_min_violation = std::numeric_limits<double>::quiet_NaN();
    double projected_llbi_max_violation = 0.0;
    double projected_llbi_avg_violation = 0.0;
    double projected_llbi_root_bound_initial = std::numeric_limits<double>::quiet_NaN();
    double projected_llbi_root_bound_final = std::numeric_limits<double>::quiet_NaN();
    double projected_llbi_root_bound_improvement_abs = 0.0;
    double projected_llbi_root_bound_improvement_pct = 0.0;
    int projected_poly_candidate_cuts_generated = 0;
    int projected_poly_candidate_cuts_added = 0;
    bool projected_poly_enumeration_truncated = false;
    int projected_poly_enumeration_limit = 0;
    int projected_exp_separated_cuts_added = 0;
    int projected_exp_separation_rounds = 0;
    int projected_exp_candidate_cuts_generated = 0;
    int projected_exp_candidate_cuts_added = 0;
    bool projected_exp_enumeration_truncated = false;
    int projected_exp_enumeration_limit = 0;
    bool projected_coverage_llbi_weighted = false;
    std::string projected_coverage_llbi_mode;
    std::string projected_coverage_llbi_weight_map_hash;
    int projected_coverage_llbi_scenarios_precomputed = 0;
    int projected_coverage_llbi_baseline_cells = 0;
    int projected_coverage_llbi_nonempty_coverage_sets = 0;
    int projected_coverage_llbi_total_incidence_terms = 0;
    int projected_coverage_llbi_separation_calls = 0;
    int projected_coverage_llbi_cuts_generated = 0;
    int projected_coverage_llbi_cuts_added = 0;
    int projected_coverage_llbi_duplicate_cuts = 0;
    double projected_coverage_llbi_max_violation = 0.0;
    double projected_coverage_llbi_precompute_time_sec = 0.0;
    double projected_coverage_llbi_separation_time_sec = 0.0;
    std::string projected_coverage_llbi_validity_mode;
    bool projected_path_llbi_weighted = false;
    std::string projected_path_llbi_mode;
    std::string projected_path_llbi_weight_map_hash;
    int projected_path_llbi_scenarios_precomputed = 0;
    int projected_path_llbi_destination_nodes = 0;
    int projected_path_llbi_total_paths = 0;
    int projected_path_llbi_total_incidence_terms = 0;
    int projected_path_llbi_nodes_without_paths = 0;
    bool projected_path_llbi_enumeration_complete = true;
    int projected_path_llbi_paths_truncated = 0;
    int projected_path_llbi_separation_calls = 0;
    int projected_path_llbi_cuts_generated = 0;
    int projected_path_llbi_cuts_added = 0;
    int projected_path_llbi_duplicate_cuts = 0;
    double projected_path_llbi_max_violation = 0.0;
    double projected_path_llbi_precompute_time_sec = 0.0;
    double projected_path_llbi_separation_time_sec = 0.0;
    std::string projected_path_llbi_validity_mode;
    bool global_dominance_enabled = false;
    bool global_dominance_structural_weight_safe = false;
    int global_dominance_original_candidate_count = 0;
    int global_dominance_candidates_removed = 0;
    int global_dominance_equivalence_classes = 0;
    int global_dominance_post_candidate_count = 0;
    int global_dominance_warm_start_replacements = 0;
    double global_dominance_precompute_time_sec = 0.0;
    bool conditional_zero_benefit_enabled = false;
    bool conditional_zero_benefit_structural_weight_safe = false;
    int conditional_zero_benefit_callback_calls = 0;
    int conditional_zero_benefit_nodes_checked = 0;
    int conditional_zero_benefit_candidates_checked = 0;
    int conditional_zero_benefit_fixings_attempted = 0;
    int conditional_zero_benefit_fixings_applied = 0;
    int conditional_zero_benefit_variables_fixed_zero = 0;
    int conditional_zero_benefit_scenarios_reachability_computed = 0;
    double conditional_zero_benefit_time_sec = 0.0;
    bool branch_benders_use_root_user_cuts = false;
    int branch_benders_root_user_cut_max_rounds = 1;
    double branch_benders_root_user_cut_tolerance = 0.0;
    int branch_benders_root_user_cut_rounds_executed = 0;
    int branch_benders_root_user_cut_callback_calls = 0;
    int branch_benders_root_user_cuts_added = 0;
    int branch_benders_root_user_cut_scenarios_solved = 0;
    double branch_benders_root_user_cut_max_violation = 0.0;
    double branch_benders_root_user_cut_total_time_sec = 0.0;
    double branch_benders_root_user_cut_subproblem_time_sec = 0.0;
    std::string branch_benders_root_user_cut_skipped_reason;
    bool branch_benders_root_user_cut_only_at_root_confirmed = true;
    std::vector<solver::BranchBendersRootUserCutRoundLog> branch_benders_root_user_cut_round_log;
    std::string fpp_mode;
    std::string formulation = "base";
    bool dominator_cuts_enabled = false;
    bool separator_cuts_enabled = false;
    bool greedy_warm_start_enabled = false;
    bool local_search_enabled = false;
    int separator_cuts_added = 0;
    int separator_min_cut_calls = 0;
    int separator_callback_invocations = 0;
    int separator_duplicate_cuts_skipped = 0;
    int separator_large_cuts_skipped = 0;
    double separator_time_sec = 0.0;
    int dominator_cuts_added = 0;
    int dominator_aggregate_cuts_added = 0;
    int dominator_individual_cuts_added = 0;
    int dominator_dag_scenarios = 0;
    int dominator_fallback_scenarios = 0;
    double dominator_preprocessing_time_sec = 0.0;
    double heuristic_time_sec = 0.0;
    double heuristic_objective = std::numeric_limits<double>::quiet_NaN();
    int heuristic_exact_evaluations = 0;
    int heuristic_selected_count = 0;
    std::vector<int> selected_firebreaks;
    bool warm_start_used = false;
    bool mip_start_accepted = false;
    int compact_node_count = 0;
    int eligible_node_count = 0;
    int total_observed_scenario_nodes = 0;
    int total_scenario_arcs = 0;
    double evaluator_objective = std::numeric_limits<double>::quiet_NaN();
    double evaluator_abs_diff = std::numeric_limits<double>::quiet_NaN();
    double evaluator_rel_diff = std::numeric_limits<double>::quiet_NaN();
    std::string weight_profile = "homogeneous";
    std::string weight_map_file;
    std::string weight_map_hash;
    int weight_replicate = 0;
    std::uint64_t weight_generation_seed = 0;
    int weight_generator_version = 0;
    std::string canonical_landscape_id;
    std::string paired_landscape_id;
    std::string weight_source_universe_hash;
    std::string weight_mapping_method;
    std::string weight_mapping_hash;
    int weight_mapped_cell_count = 0;
    int weight_missing_cell_count = 0;
    std::string paired_reburn_instance_id;
    bool paired_evaluation_enabled = false;
    bool weight_normalized = false;
    double weight_mean = std::numeric_limits<double>::quiet_NaN();
    double weight_min = std::numeric_limits<double>::quiet_NaN();
    double weight_max = std::numeric_limits<double>::quiet_NaN();
    double weight_total = std::numeric_limits<double>::quiet_NaN();
    double solver_weighted_objective = std::numeric_limits<double>::quiet_NaN();
    double evaluator_weighted_objective = std::numeric_limits<double>::quiet_NaN();
    double objective_validation_abs_difference = std::numeric_limits<double>::quiet_NaN();
    double objective_validation_rel_difference = std::numeric_limits<double>::quiet_NaN();
    bool objective_validation_passed = false;
    double train_expected_weighted_burn_loss = std::numeric_limits<double>::quiet_NaN();
    double test_expected_weighted_burn_loss = std::numeric_limits<double>::quiet_NaN();
    double train_weighted_var = std::numeric_limits<double>::quiet_NaN();
    double test_weighted_var = std::numeric_limits<double>::quiet_NaN();
    double train_weighted_cvar = std::numeric_limits<double>::quiet_NaN();
    double test_weighted_cvar = std::numeric_limits<double>::quiet_NaN();
    double train_percentage_landscape_value_burned = std::numeric_limits<double>::quiet_NaN();
    double test_percentage_landscape_value_burned = std::numeric_limits<double>::quiet_NaN();
    double train_percentage_high_value_weight_burned = std::numeric_limits<double>::quiet_NaN();
    double test_percentage_high_value_weight_burned = std::numeric_limits<double>::quiet_NaN();
    bool dpv_weighted = false;
    bool dpv_model_weighted = false;
    std::string dpv_model_type;
    std::string dpv_variant;
    std::string dpv_structural_definition;
    std::string dpv_ignition_policy;
    std::string dpv_weight_profile;
    std::string dpv_weight_map_hash;
    std::string dpv_scenario_aggregation;
    std::string dpv_normalization;
    std::string dpv_risk_measure;
    int dpv_candidates_scored = 0;
    int dpv_candidates_selected = 0;
    double dpv_score_min = std::numeric_limits<double>::quiet_NaN();
    double dpv_score_max = std::numeric_limits<double>::quiet_NaN();
    double dpv_score_mean = std::numeric_limits<double>::quiet_NaN();
    double dpv_selected_score_sum = std::numeric_limits<double>::quiet_NaN();
    bool dpv_structural_cache_hit = false;
    bool dpv_weighted_cache_hit = false;
    double dpv_score_precompute_time_sec = std::numeric_limits<double>::quiet_NaN();
    double dpv_selection_time_sec = std::numeric_limits<double>::quiet_NaN();
    double dpv_surrogate_objective = std::numeric_limits<double>::quiet_NaN();
    double dpv_surrogate_best_bound = std::numeric_limits<double>::quiet_NaN();
    double dpv_surrogate_gap = std::numeric_limits<double>::quiet_NaN();
    int dpv_benders_iterations = 0;
    int dpv_benders_subproblems_solved = 0;
    int dpv_benders_cuts_generated = 0;
    int dpv_benders_cuts_added = 0;
    int dpv_benders_duplicate_cuts = 0;
    double dpv_benders_max_cut_violation = 0.0;
    double dpv_benders_max_tightness_error = 0.0;
    double dpv_benders_subproblem_time_sec = 0.0;
    double dpv_benders_cut_time_sec = 0.0;
    bool dpv_llbi_enabled = false;
    bool dpv_llbi_weighted = false;
    std::string dpv_llbi_type;
    int dpv_llbi_constraints_added = 0;
    double dpv_llbi_precompute_time_sec = 0.0;
    std::string dpv_llbi_validity_mode;
    int dpv_greedy_iterations = 0;
    int dpv_score_recomputations = 0;
    int dpv_marginal_scores_evaluated = 0;
    double dpv_overlap_value_removed = std::numeric_limits<double>::quiet_NaN();
    std::string risk_measure = "expected";
    double cvar_beta = 0.9;
    double cvar_lambda = 1.0;
    double risk_threshold_value = std::numeric_limits<double>::quiet_NaN();
    double expected_loss_component = std::numeric_limits<double>::quiet_NaN();
    double cvar_loss_component = std::numeric_limits<double>::quiet_NaN();
    double train_empirical_var_burned_area = std::numeric_limits<double>::quiet_NaN();
    double train_empirical_cvar_burned_area = std::numeric_limits<double>::quiet_NaN();
    double test_empirical_var_burned_area = std::numeric_limits<double>::quiet_NaN();
    double test_empirical_cvar_burned_area = std::numeric_limits<double>::quiet_NaN();
    std::string validation_status;
    std::string warm_start_source;
    std::vector<int> warm_start_valid_nodes;
    std::vector<int> warm_start_ignored_nodes;
    std::vector<std::string> warm_start_notes;
    bool restricted_candidate_enabled = false;
    bool restricted_candidate_exact_mode = false;
    bool restricted_candidate_bounds_enabled = false;
    bool restricted_candidate_bounds_weighted = false;
    std::string restricted_candidate_bound_type = "none";
    std::string restricted_candidate_bound_map_hash;
    int restricted_candidates_evaluated_by_bound = 0;
    int restricted_candidates_permanently_pruned = 0;
    int restricted_candidates_not_pruned_due_to_safety = 0;
    bool restricted_candidate_early_exactness_certificate_used = false;
    bool restricted_candidate_full_activation_avoided = false;
    bool restricted_candidate_unvalidated_bound_rejected = false;
    std::string restricted_candidate_initial_policy;
    std::string restricted_candidate_activation_policy;
    int restricted_candidate_initial_active_count = 0;
    int restricted_candidate_final_active_count = 0;
    double restricted_candidate_final_active_fraction = 0.0;
    bool restricted_candidate_eventually_activated_all = false;
    bool restricted_candidate_full_activation_performed = false;
    bool restricted_candidate_restricted_lower_bound_is_global = false;
    bool restricted_candidate_final_lower_bound_is_global = false;
    bool restricted_candidate_cut_reuse_enabled = false;
    int restricted_candidate_cut_pool_size = 0;
    int restricted_candidate_cut_pool_peak_size = 0;
    int restricted_candidate_cut_pool_evictions = 0;
    int restricted_candidate_cut_pool_reinstantiations = 0;
    int restricted_candidate_rounds = 0;
    int restricted_candidate_cuts_reused_in_full_stage = 0;
    int restricted_candidate_duplicate_cuts_skipped = 0;
    bool restricted_candidate_heuristic_mode_enabled = false;
    bool restricted_candidate_stopped_before_full_activation = false;
    bool restricted_candidate_global_optimality_certified = false;
    bool restricted_candidate_global_time_budget_enabled = false;
    bool restricted_candidate_time_budget_exhausted = false;
    std::string restricted_candidate_reason_for_heuristic_stop;
    double restricted_candidate_global_time_limit_seconds = 0.0;
    double restricted_candidate_elapsed_time_total_seconds = 0.0;
    double restricted_candidate_initial_stage_runtime = 0.0;
    double restricted_candidate_activation_stage_runtime_total = 0.0;
    double restricted_candidate_final_full_stage_runtime = 0.0;
    double restricted_candidate_final_stage_time_limit = 0.0;
    double restricted_candidate_restricted_objective = std::numeric_limits<double>::quiet_NaN();
    double restricted_candidate_restricted_best_bound = std::numeric_limits<double>::quiet_NaN();
    bool restricted_candidate_restricted_bound_is_global = false;
    double restricted_candidate_active_fraction_at_stop = 0.0;
    std::string restricted_candidate_maintenance_policy = "none";
    bool restricted_candidate_maintenance_weighted = false;
    std::string restricted_candidate_maintenance_map_hash;
    bool restricted_candidate_deactivation_enabled = false;
    int restricted_candidate_deactivation_rounds = 0;
    int restricted_candidate_active_target = 0;
    int restricted_candidate_considered_for_deactivation = 0;
    int restricted_candidate_deactivated_total = 0;
    int restricted_candidate_reactivated_total = 0;
    int restricted_candidate_protected_from_deactivation_total = 0;
    bool restricted_candidate_full_activation_overrode_maintenance = false;
    int restricted_candidate_min_active_size = 0;
    int restricted_candidate_max_active_size = 0;
    int restricted_candidate_deactivation_batch_size = 0;
    int restricted_candidate_deactivation_min_age = 1;
    int restricted_candidate_reactivation_cooldown_rounds = 1;
    bool restricted_candidate_protect_selected_candidates = true;
    int restricted_candidate_protected_selected_count = 0;
    int restricted_candidate_protected_min_age_count = 0;
    int restricted_candidate_protected_cooldown_count = 0;
    int restricted_candidate_protected_newly_activated_count = 0;
    int restricted_candidate_protected_tail_count = 0;
    int restricted_candidate_deactivation_candidate_count = 0;
    int restricted_candidate_reactivation_blocked_by_cooldown_count = 0;
    int restricted_candidate_oscillation_event_count = 0;
    int restricted_candidate_max_state_changes = 0;
    double restricted_candidate_average_state_changes = 0.0;
    std::string restricted_candidate_score_mode = "generic";
    double restricted_candidate_tail_score_gamma = 0.5;
    int restricted_candidate_tail_protection_size = 0;
    std::string restricted_candidate_scorer = "none";
    bool restricted_candidate_scorer_weighted = false;
    std::string restricted_candidate_score_map_hash;
    std::vector<int> restricted_initial_candidate_ids;
    std::vector<std::pair<int, double>> restricted_initial_candidate_scores;
    int restricted_score_recomputations = 0;
    std::vector<int> restricted_candidates_activated_by_score;
    std::vector<int> restricted_candidates_activated_by_full_fallback;
    int restricted_candidate_deactivation_blocked_by_tail_protection_count = 0;
    int restricted_candidate_activated_by_tail_blend_count = 0;
    int restricted_candidate_activated_tail_top_k_overlap = 0;
    int restricted_candidate_deactivated_tail_top_k_warning_count = 0;
    std::vector<std::vector<int>> restricted_candidate_tail_protected_candidates_by_round;
    std::vector<int> restricted_candidate_tail_protected_count_by_round;
    bool restricted_candidate_persistent_subproblems_enabled = false;
    int restricted_candidate_subproblem_model_build_count = 0;
    int restricted_candidate_subproblem_fixed_y_update_count = 0;
    int restricted_candidate_subproblem_solve_count = 0;
    int restricted_candidate_subproblem_model_rebuild_count = 0;
    double restricted_candidate_subproblem_total_build_time = 0.0;
    double restricted_candidate_subproblem_total_update_time = 0.0;
    double restricted_candidate_subproblem_total_solve_time = 0.0;
    double restricted_candidate_subproblem_average_update_time = 0.0;
    double restricted_candidate_subproblem_average_solve_time = 0.0;
    bool restricted_candidate_persistent_master_enabled = false;
    int restricted_candidate_master_model_build_count = 0;
    int restricted_candidate_master_model_rebuild_count = 0;
    int restricted_candidate_master_bound_update_count = 0;
    int restricted_candidate_master_cut_insertions = 0;
    int restricted_candidate_master_duplicate_cut_insertions_skipped = 0;
    double restricted_candidate_master_total_build_time = 0.0;
    double restricted_candidate_master_total_bound_update_time = 0.0;
    double restricted_candidate_master_total_cut_insertion_time = 0.0;
    std::string restricted_candidate_persistent_master_note;
    std::vector<RestrictedCandidateRoundResult> restricted_candidate_round_log;
    bool restricted_candidate_tail_score_diagnostics_enabled = false;
    std::vector<benders::CvarTailScoreRoundDiagnostics>
        restricted_candidate_tail_score_diagnostics;
    double train_expected_burned_area = 0.0;
    double train_worst_10pct_burned_area = 0.0;
    double test_expected_burned_area = 0.0;
    double test_worst_10pct_burned_area = 0.0;
    double train_evaluation_runtime_seconds = 0.0;
    double test_evaluation_runtime_seconds = 0.0;
    double test_scenario_loading_runtime_seconds = 0.0;
    std::string train_graph_classification_ratios;
    std::string test_graph_classification_ratios;
    std::string graph_type_note = "Cell2Fire scenarios are treated as directed propagation graphs.";
    std::vector<std::string> notes;
};

std::string current_timestamp_utc();

void write_experiment_result_json(
    const std::filesystem::path& output_path,
    const StandardExperimentResult& result);

void append_experiment_result_csv(
    const std::filesystem::path& output_path,
    const StandardExperimentResult& result);

}  // namespace firebreak::io
