#pragma once

#include <cstddef>
#include <limits>
#include <string>
#include <utility>
#include <vector>

namespace firebreak::solver {

struct BendersIterationLog {
    int iteration = 0;
    double master_objective = 0.0;
    double master_best_bound = 0.0;
    double total_subproblem_objective = 0.0;
    double weighted_recourse_objective = 0.0;
    double max_cut_violation = 0.0;
    double avg_cut_violation = 0.0;
    int cuts_added = 0;
    int cumulative_cuts = 0;
    int subproblems_attempted = 0;
    int subproblems_solved = 0;
    double master_time_sec = 0.0;
    double subproblem_time_sec = 0.0;
    double average_subproblem_time_sec = 0.0;
    double max_subproblem_time_sec = 0.0;
    double iteration_time_sec = 0.0;
    int selected_firebreak_count = 0;
    std::vector<int> selected_firebreaks;
};

struct BendersAddedCutRecord {
    int iteration = 0;
    int scenario_id = 0;
    double subproblem_value = 0.0;
    double violation = 0.0;
    double rhs_constant = 0.0;
    std::vector<std::pair<int, double>> coefficients_by_compact_index;
};

struct BendersLiftedLowerBoundRecord {
    int scenario_id = 0;
    double f_empty = 0.0;
    double rhs_constant = 0.0;
    int num_nonzero_coefficients = 0;
    std::vector<std::pair<int, double>> coefficients_by_compact_index;
};

struct BranchBendersIncumbentLog {
    int incumbent_index = 0;
    double incumbent_objective = 0.0;
    int selected_firebreak_count = 0;
    int cuts_added = 0;
    double max_cut_violation = 0.0;
    int subproblems_attempted = 0;
    int subproblems_solved = 0;
    double subproblem_time_sec = 0.0;
    double average_subproblem_time_sec = 0.0;
    double max_subproblem_time_sec = 0.0;
    double cut_construction_time_sec = 0.0;
    double lazy_cut_insertion_time_sec = 0.0;
    int violated_cuts = 0;
    int nonviolated_cuts = 0;
    int skipped_cuts = 0;
    int duplicate_cuts = 0;
};

struct BranchBendersRootUserCutRoundLog {
    int round_index = 0;
    int scenarios_solved = 0;
    int cuts_added = 0;
    double max_violation = 0.0;
    double avg_violation = 0.0;
    double time_sec = 0.0;
};

struct ModelResult {
    std::string method;
    std::string status;
    double objective_value = 0.0;
    double best_bound = 0.0;
    double mip_gap = 0.0;
    double runtime_seconds = 0.0;
    int solver_status_code = 0;
    long long explored_nodes = -1;
    std::vector<int> selected_firebreak_indices;
    std::vector<int> selected_firebreak_original_nodes;
    std::size_t num_variables = 0;
    std::size_t num_constraints = 0;
    int iterations = 0;
    int cuts_added = 0;
    double max_cut_violation = 0.0;
    std::string benders_status;
    std::string benders_termination_reason;
    int benders_iterations = 0;
    int benders_cuts_added = 0;
    double benders_final_max_cut_violation = 0.0;
    double benders_largest_intermediate_cut_violation = 0.0;
    double benders_master_solve_time_sec = 0.0;
    double benders_subproblem_time_sec = 0.0;
    int benders_subproblems_solved = 0;
    double benders_average_subproblem_time_sec = 0.0;
    double benders_max_subproblem_time_sec = 0.0;
    bool benders_use_lifted_lower_bounds = false;
    int benders_lifted_lower_bound_count = 0;
    double benders_lifted_lower_bound_precompute_time_sec = 0.0;
    int benders_lifted_lower_bound_nonzero_coefficients = 0;
    double benders_lifted_lower_bound_min_rhs = std::numeric_limits<double>::quiet_NaN();
    double benders_lifted_lower_bound_max_rhs = std::numeric_limits<double>::quiet_NaN();
    bool benders_lifted_lower_bound_weighted = false;
    std::string benders_lifted_lower_bound_weight_map_hash;
    int benders_lifted_lower_bound_scenarios_precomputed = 0;
    int benders_lifted_lower_bound_singletons_evaluated = 0;
    double benders_lifted_lower_bound_no_firebreak_loss_min =
        std::numeric_limits<double>::quiet_NaN();
    double benders_lifted_lower_bound_no_firebreak_loss_max =
        std::numeric_limits<double>::quiet_NaN();
    double benders_lifted_lower_bound_singleton_benefit_min =
        std::numeric_limits<double>::quiet_NaN();
    double benders_lifted_lower_bound_singleton_benefit_max =
        std::numeric_limits<double>::quiet_NaN();
    int benders_lifted_lower_bound_constraints_added = 0;
    bool benders_lifted_lower_bound_cache_hit = false;
    std::string benders_lifted_lower_bound_validity_mode;
    std::vector<std::string> benders_lifted_lower_bound_notes;
    std::vector<BendersIterationLog> benders_iteration_log;
    std::vector<BendersAddedCutRecord> benders_added_cuts;
    std::vector<BendersLiftedLowerBoundRecord> benders_lifted_lower_bounds;
    bool branch_benders_enabled = false;
    int branch_benders_callback_calls = 0;
    int branch_benders_candidate_callback_calls = 0;
    int branch_benders_incumbent_callback_calls = 0;
    int branch_benders_candidate_incumbents_checked = 0;
    int branch_benders_subproblems_attempted = 0;
    int branch_benders_subproblems_solved = 0;
    int branch_benders_lazy_cuts_added = 0;
    double branch_benders_max_cut_violation = 0.0;
    double branch_benders_largest_incumbent_cut_violation = 0.0;
    double branch_benders_callback_time_sec = 0.0;
    double branch_benders_subproblem_time_sec = 0.0;
    double branch_benders_average_subproblem_time_sec = 0.0;
    double branch_benders_max_subproblem_time_sec = 0.0;
    double branch_benders_cut_construction_time_sec = 0.0;
    double branch_benders_lazy_cut_insertion_time_sec = 0.0;
    int branch_benders_violated_cuts = 0;
    int branch_benders_nonviolated_cuts = 0;
    int branch_benders_skipped_cuts = 0;
    int branch_benders_duplicate_cuts = 0;
    std::vector<BranchBendersIncumbentLog> branch_benders_incumbent_log;
    bool combinatorial_benders_enabled = false;
    std::string combinatorial_benders_lift_mode = "heuristic";
    std::string combinatorial_benders_scenario_order = "eta-asc";
    double combinatorial_benders_cut_sampling_ratio = 0.10;
    bool combinatorial_benders_fractional_separation_enabled = true;
    bool combinatorial_benders_initial_cuts_enabled = true;
    int combinatorial_benders_integer_cuts_added = 0;
    int combinatorial_benders_fractional_cuts_added = 0;
    int combinatorial_benders_initial_cuts_added = 0;
    int combinatorial_benders_scenarios_checked = 0;
    double combinatorial_benders_separation_time_sec = 0.0;
    double combinatorial_benders_avg_paths_per_cut = 0.0;
    double combinatorial_benders_avg_cut_nonzeros = 0.0;
    int combinatorial_benders_num_violated_cuts = 0;
    bool combinatorial_benders_weighted = false;
    std::string combinatorial_benders_mode;
    std::string combinatorial_benders_weight_map_hash;
    int combinatorial_benders_weighted_recourse_evaluations = 0;
    int combinatorial_benders_duplicate_cuts = 0;
    int combinatorial_benders_cuts_tight_at_incumbent = 0;
    bool combinatorial_benders_lifting_enabled = false;
    bool combinatorial_benders_scenario_sampling_enabled = false;
    double combinatorial_benders_max_tightness_error = 0.0;
    double combinatorial_benders_max_violation = 0.0;
    double combinatorial_benders_propagation_time_sec = 0.0;
    double combinatorial_benders_cut_build_time_sec = 0.0;
    std::string combinatorial_benders_validity_mode;
    bool combinatorial_weighted = false;
    std::string combinatorial_mode;
    std::string combinatorial_weight_map_hash;
    int combinatorial_candidate_callbacks = 0;
    int combinatorial_scenarios_evaluated = 0;
    int combinatorial_weighted_recourse_evaluations = 0;
    int combinatorial_cuts_generated = 0;
    int combinatorial_cuts_added = 0;
    int combinatorial_duplicate_cuts = 0;
    int combinatorial_cuts_tight_at_incumbent = 0;
    double combinatorial_max_tightness_error = 0.0;
    double combinatorial_max_violation = 0.0;
    double combinatorial_propagation_time_sec = 0.0;
    double combinatorial_cut_build_time_sec = 0.0;
    double combinatorial_callback_time_sec = 0.0;
    std::string combinatorial_validity_mode;
    bool combinatorial_lifting_enabled = false;
    bool combinatorial_fractional_cuts_enabled = false;
    bool combinatorial_initial_cuts_enabled = false;
    bool combinatorial_scenario_sampling_enabled = false;
    bool coverage_llbi_enabled = false;
    int coverage_llbi_num_zeta_vars = 0;
    int coverage_llbi_num_constraints = 0;
    double coverage_llbi_precompute_time_sec = 0.0;
    bool coverage_llbi_weighted = false;
    std::string coverage_llbi_weight_map_hash;
    int coverage_llbi_scenarios_precomputed = 0;
    int coverage_llbi_baseline_cells = 0;
    int coverage_llbi_auxiliary_variables = 0;
    int coverage_llbi_linking_constraints = 0;
    int coverage_llbi_loss_constraints = 0;
    int coverage_llbi_nonempty_coverage_sets = 0;
    int coverage_llbi_total_incidence_terms = 0;
    double coverage_llbi_build_time_sec = 0.0;
    std::string coverage_llbi_validity_mode;
    bool path_llbi_enabled = false;
    int path_llbi_num_b_vars = 0;
    int path_llbi_num_path_constraints = 0;
    int path_llbi_num_paths_used = 0;
    bool path_llbi_weighted = false;
    std::string path_llbi_weight_map_hash;
    int path_llbi_scenarios_precomputed = 0;
    int path_llbi_baseline_nodes = 0;
    int path_llbi_auxiliary_variables = 0;
    int path_llbi_path_constraints = 0;
    int path_llbi_loss_constraints = 0;
    int path_llbi_total_paths = 0;
    int path_llbi_total_candidate_incidence_terms = 0;
    int path_llbi_nodes_without_paths = 0;
    bool path_llbi_path_enumeration_complete = true;
    int path_llbi_paths_truncated = 0;
    double path_llbi_precompute_time_sec = 0.0;
    double path_llbi_build_time_sec = 0.0;
    std::string path_llbi_validity_mode;
    bool projected_coverage_llbi_enabled = false;
    bool projected_path_llbi_enabled = false;
    std::string projected_llbi_family;
    std::string projected_llbi_strategy;
    std::string projected_llbi_mode;
    int projected_llbi_root_rounds = 0;
    int projected_llbi_cuts_added = 0;
    int projected_llbi_coverage_cuts_added = 0;
    int projected_llbi_path_cuts_added = 0;
    int projected_llbi_violated_cuts_found = 0;
    double projected_llbi_separation_time_sec = 0.0;
    double projected_llbi_solve_time_sec = 0.0;
    double projected_llbi_total_time_sec = 0.0;
    int projected_llbi_total_nonzeros = 0;
    double projected_llbi_avg_nonzeros_per_cut = 0.0;
    int projected_llbi_max_nonzeros_per_cut = 0;
    double projected_llbi_min_violation = std::numeric_limits<double>::quiet_NaN();
    double projected_llbi_max_violation = 0.0;
    double projected_llbi_avg_violation = 0.0;
    double projected_llbi_root_bound_initial = std::numeric_limits<double>::quiet_NaN();
    double projected_llbi_root_bound_final = std::numeric_limits<double>::quiet_NaN();
    double projected_llbi_root_bound_improvement_abs = 0.0;
    double projected_llbi_root_bound_improvement_pct = 0.0;
    int projected_poly_candidate_cuts_generated = 0;
    int projected_poly_candidate_cuts_added = 0;
    bool projected_poly_enumeration_truncated = false;
    int projected_poly_enumeration_limit = 0;
    int projected_exp_separated_cuts_added = 0;
    int projected_exp_separation_rounds = 0;
    int projected_exp_candidate_cuts_generated = 0;
    int projected_exp_candidate_cuts_added = 0;
    bool projected_exp_enumeration_truncated = false;
    int projected_exp_enumeration_limit = 0;
    bool projected_coverage_llbi_weighted = false;
    std::string projected_coverage_llbi_mode;
    std::string projected_coverage_llbi_weight_map_hash;
    int projected_coverage_llbi_scenarios_precomputed = 0;
    int projected_coverage_llbi_baseline_cells = 0;
    int projected_coverage_llbi_nonempty_coverage_sets = 0;
    int projected_coverage_llbi_total_incidence_terms = 0;
    int projected_coverage_llbi_separation_calls = 0;
    int projected_coverage_llbi_cuts_generated = 0;
    int projected_coverage_llbi_cuts_added = 0;
    int projected_coverage_llbi_duplicate_cuts = 0;
    double projected_coverage_llbi_max_violation = 0.0;
    double projected_coverage_llbi_precompute_time_sec = 0.0;
    double projected_coverage_llbi_separation_time_sec = 0.0;
    std::string projected_coverage_llbi_validity_mode;
    bool projected_path_llbi_weighted = false;
    std::string projected_path_llbi_mode;
    std::string projected_path_llbi_weight_map_hash;
    int projected_path_llbi_scenarios_precomputed = 0;
    int projected_path_llbi_destination_nodes = 0;
    int projected_path_llbi_total_paths = 0;
    int projected_path_llbi_total_incidence_terms = 0;
    int projected_path_llbi_nodes_without_paths = 0;
    bool projected_path_llbi_enumeration_complete = true;
    int projected_path_llbi_paths_truncated = 0;
    int projected_path_llbi_separation_calls = 0;
    int projected_path_llbi_cuts_generated = 0;
    int projected_path_llbi_cuts_added = 0;
    int projected_path_llbi_duplicate_cuts = 0;
    double projected_path_llbi_max_violation = 0.0;
    double projected_path_llbi_precompute_time_sec = 0.0;
    double projected_path_llbi_separation_time_sec = 0.0;
    std::string projected_path_llbi_validity_mode;
    bool global_dominance_enabled = false;
    bool global_dominance_structural_weight_safe = false;
    int global_dominance_original_candidate_count = 0;
    int global_dominance_candidates_removed = 0;
    int global_dominance_equivalence_classes = 0;
    int global_dominance_post_candidate_count = 0;
    int global_dominance_warm_start_replacements = 0;
    double global_dominance_precompute_time_sec = 0.0;
    bool conditional_zero_benefit_enabled = false;
    bool conditional_zero_benefit_structural_weight_safe = false;
    int conditional_zero_benefit_callback_calls = 0;
    int conditional_zero_benefit_nodes_checked = 0;
    int conditional_zero_benefit_candidates_checked = 0;
    int conditional_zero_benefit_fixings_attempted = 0;
    int conditional_zero_benefit_fixings_applied = 0;
    int conditional_zero_benefit_variables_fixed_zero = 0;
    int conditional_zero_benefit_scenarios_reachability_computed = 0;
    double conditional_zero_benefit_time_sec = 0.0;
    bool branch_benders_use_root_user_cuts = false;
    int branch_benders_root_user_cut_max_rounds = 1;
    double branch_benders_root_user_cut_tolerance = 0.0;
    int branch_benders_root_user_cut_rounds_executed = 0;
    int branch_benders_root_user_cut_callback_calls = 0;
    int branch_benders_root_user_cuts_added = 0;
    int branch_benders_root_user_cut_scenarios_solved = 0;
    double branch_benders_root_user_cut_max_violation = 0.0;
    double branch_benders_root_user_cut_total_time_sec = 0.0;
    double branch_benders_root_user_cut_subproblem_time_sec = 0.0;
    std::string branch_benders_root_user_cut_skipped_reason;
    bool branch_benders_root_user_cut_only_at_root_confirmed = true;
    std::vector<BranchBendersRootUserCutRoundLog> branch_benders_root_user_cut_round_log;
    std::string fpp_mode;
    std::string formulation = "base";
    bool dominator_cuts_enabled = false;
    bool separator_cuts_enabled = false;
    bool greedy_warm_start_enabled = false;
    bool local_search_enabled = false;
    int separator_cuts_added = 0;
    int separator_min_cut_calls = 0;
    int separator_callback_invocations = 0;
    int separator_duplicate_cuts_skipped = 0;
    int separator_large_cuts_skipped = 0;
    double separator_time_sec = 0.0;
    int dominator_cuts_added = 0;
    int dominator_aggregate_cuts_added = 0;
    int dominator_individual_cuts_added = 0;
    int dominator_dag_scenarios = 0;
    int dominator_fallback_scenarios = 0;
    double dominator_preprocessing_time_sec = 0.0;
    double heuristic_time_sec = 0.0;
    double heuristic_objective = std::numeric_limits<double>::quiet_NaN();
    int heuristic_exact_evaluations = 0;
    int heuristic_selected_count = 0;
    bool warm_start_used = false;
    bool mip_start_accepted = false;
    int compact_node_count = 0;
    int eligible_node_count = 0;
    int total_observed_scenario_nodes = 0;
    int total_scenario_arcs = 0;
    double evaluator_objective = std::numeric_limits<double>::quiet_NaN();
    double evaluator_abs_diff = std::numeric_limits<double>::quiet_NaN();
    double evaluator_rel_diff = std::numeric_limits<double>::quiet_NaN();
    std::string objective_metric;
    std::string weight_profile = "homogeneous";
    std::string weight_map_file;
    std::string weight_map_hash;
    bool weight_normalized = false;
    double weight_mean = std::numeric_limits<double>::quiet_NaN();
    double weight_min = std::numeric_limits<double>::quiet_NaN();
    double weight_max = std::numeric_limits<double>::quiet_NaN();
    double weight_total = std::numeric_limits<double>::quiet_NaN();
    double solver_weighted_objective = std::numeric_limits<double>::quiet_NaN();
    double evaluator_weighted_objective = std::numeric_limits<double>::quiet_NaN();
    double objective_validation_abs_difference = std::numeric_limits<double>::quiet_NaN();
    double objective_validation_rel_difference = std::numeric_limits<double>::quiet_NaN();
    bool objective_validation_passed = false;
    std::string risk_measure = "expected";
    double cvar_beta = 0.9;
    double cvar_lambda = 1.0;
    double risk_threshold_value = std::numeric_limits<double>::quiet_NaN();
    double expected_loss_component = std::numeric_limits<double>::quiet_NaN();
    double cvar_loss_component = std::numeric_limits<double>::quiet_NaN();
    double train_empirical_var_burned_area = std::numeric_limits<double>::quiet_NaN();
    double train_empirical_cvar_burned_area = std::numeric_limits<double>::quiet_NaN();
    double test_empirical_var_burned_area = std::numeric_limits<double>::quiet_NaN();
    double test_empirical_cvar_burned_area = std::numeric_limits<double>::quiet_NaN();
    std::string validation_status;
    std::string warm_start_source;
    std::vector<int> warm_start_valid_nodes;
    std::vector<int> warm_start_ignored_nodes;
    std::vector<std::string> warm_start_notes;
    std::vector<std::string> notes;
};

}  // namespace firebreak::solver
