#pragma once

#include <filesystem>
#include <limits>
#include <string>
#include <vector>

#include "benders/BendersCut.hpp"
#include "opt/OptimizationInstance.hpp"

namespace firebreak::benders {

enum class FppProjectedLlbiFamily {
    Coverage,
    Path,
};

enum class FppProjectedLlbiMode {
    None,
    // Exponential projected family, generated by separation/enumeration.
    Exp,
    // Polynomial-size static projected subset.
    Poly,
};

struct FppProjectedLlbiOptions {
    bool use_projected_coverage_llbi_exp = false;
    bool use_projected_path_llbi_exp = false;
    bool use_projected_coverage_llbi_poly = false;
    bool use_projected_path_llbi_poly = false;
    int root_rounds = 3;
    int max_cuts_per_round = 100;
    double violation_tolerance = 1.0e-6;
    int cut_density_limit = 0;
    int poly_max_cuts = 100000;
    int path_max_paths_per_node = 8;
    std::filesystem::path export_cuts_path;
};

struct FppProjectedLlbiSeparatedCut {
    BendersCut cut;
    int scenario_index = -1;
    double violation = 0.0;
    int nonzeros = 0;
};

struct FppProjectedLlbiSeparationResult {
    std::vector<FppProjectedLlbiSeparatedCut> cuts;
    int scenarios_checked = 0;
    int violated_cuts_found = 0;
    double separation_time_sec = 0.0;
    double min_violation = std::numeric_limits<double>::quiet_NaN();
    double max_violation = 0.0;
    double sum_violation = 0.0;
    bool projected_coverage_llbi_weighted = false;
    std::string projected_coverage_llbi_mode;
    std::string projected_coverage_llbi_weight_map_hash;
    int projected_coverage_llbi_scenarios_precomputed = 0;
    int projected_coverage_llbi_baseline_cells = 0;
    int projected_coverage_llbi_nonempty_coverage_sets = 0;
    int projected_coverage_llbi_total_incidence_terms = 0;
    double projected_coverage_llbi_precompute_time_sec = 0.0;
    std::string projected_coverage_llbi_validity_mode;
    bool projected_path_llbi_weighted = false;
    std::string projected_path_llbi_mode;
    std::string projected_path_llbi_weight_map_hash;
    int projected_path_llbi_scenarios_precomputed = 0;
    int projected_path_llbi_destination_nodes = 0;
    int projected_path_llbi_total_paths = 0;
    int projected_path_llbi_total_incidence_terms = 0;
    int projected_path_llbi_nodes_without_paths = 0;
    bool projected_path_llbi_enumeration_complete = true;
    int projected_path_llbi_paths_truncated = 0;
    double projected_path_llbi_precompute_time_sec = 0.0;
    std::string projected_path_llbi_validity_mode;
};

struct FppProjectedLlbiStats {
    bool projected_coverage_llbi_enabled = false;
    bool projected_path_llbi_enabled = false;
    std::string projected_llbi_family;
    std::string projected_llbi_strategy;
    std::string projected_llbi_mode;
    int projected_llbi_root_rounds = 0;
    int projected_llbi_cuts_added = 0;
    int projected_llbi_coverage_cuts_added = 0;
    int projected_llbi_path_cuts_added = 0;
    int projected_llbi_violated_cuts_found = 0;
    double projected_llbi_separation_time_sec = 0.0;
    double projected_llbi_solve_time_sec = 0.0;
    double projected_llbi_total_time_sec = 0.0;
    int projected_llbi_total_nonzeros = 0;
    double projected_llbi_avg_nonzeros_per_cut = 0.0;
    int projected_llbi_max_nonzeros_per_cut = 0;
    double projected_llbi_min_violation = std::numeric_limits<double>::quiet_NaN();
    double projected_llbi_max_violation = 0.0;
    double projected_llbi_avg_violation = 0.0;
    double projected_llbi_root_bound_initial = std::numeric_limits<double>::quiet_NaN();
    double projected_llbi_root_bound_final = std::numeric_limits<double>::quiet_NaN();
    double projected_llbi_root_bound_improvement_abs = 0.0;
    double projected_llbi_root_bound_improvement_pct = 0.0;
    int projected_poly_candidate_cuts_generated = 0;
    int projected_poly_candidate_cuts_added = 0;
    bool projected_poly_enumeration_truncated = false;
    int projected_poly_enumeration_limit = 0;
    int projected_exp_separated_cuts_added = 0;
    int projected_exp_separation_rounds = 0;
    int projected_exp_candidate_cuts_generated = 0;
    int projected_exp_candidate_cuts_added = 0;
    bool projected_exp_enumeration_truncated = false;
    int projected_exp_enumeration_limit = 0;
    bool projected_coverage_llbi_weighted = false;
    std::string projected_coverage_llbi_mode;
    std::string projected_coverage_llbi_weight_map_hash;
    int projected_coverage_llbi_scenarios_precomputed = 0;
    int projected_coverage_llbi_baseline_cells = 0;
    int projected_coverage_llbi_nonempty_coverage_sets = 0;
    int projected_coverage_llbi_total_incidence_terms = 0;
    int projected_coverage_llbi_separation_calls = 0;
    int projected_coverage_llbi_cuts_generated = 0;
    int projected_coverage_llbi_cuts_added = 0;
    int projected_coverage_llbi_duplicate_cuts = 0;
    double projected_coverage_llbi_max_violation = 0.0;
    double projected_coverage_llbi_precompute_time_sec = 0.0;
    double projected_coverage_llbi_separation_time_sec = 0.0;
    std::string projected_coverage_llbi_validity_mode;
    bool projected_path_llbi_weighted = false;
    std::string projected_path_llbi_mode;
    std::string projected_path_llbi_weight_map_hash;
    int projected_path_llbi_scenarios_precomputed = 0;
    int projected_path_llbi_destination_nodes = 0;
    int projected_path_llbi_total_paths = 0;
    int projected_path_llbi_total_incidence_terms = 0;
    int projected_path_llbi_nodes_without_paths = 0;
    bool projected_path_llbi_enumeration_complete = true;
    int projected_path_llbi_paths_truncated = 0;
    int projected_path_llbi_separation_calls = 0;
    int projected_path_llbi_cuts_generated = 0;
    int projected_path_llbi_cuts_added = 0;
    int projected_path_llbi_duplicate_cuts = 0;
    double projected_path_llbi_max_violation = 0.0;
    double projected_path_llbi_precompute_time_sec = 0.0;
    double projected_path_llbi_separation_time_sec = 0.0;
    std::string projected_path_llbi_validity_mode;
};

FppProjectedLlbiMode active_projected_llbi_mode(const FppProjectedLlbiOptions& options);
FppProjectedLlbiFamily active_projected_llbi_family(const FppProjectedLlbiOptions& options);
std::string to_string(FppProjectedLlbiMode mode);
std::string to_string(FppProjectedLlbiFamily family);
void validate_fpp_projected_llbi_options(const FppProjectedLlbiOptions& options);

std::vector<BendersCut> build_fpp_projected_llbi_poly_cuts(
    const opt::OptimizationInstance& opt,
    const FppProjectedLlbiOptions& options,
    FppProjectedLlbiStats* stats = nullptr);

FppProjectedLlbiSeparationResult separate_fpp_projected_llbi_cuts(
    const opt::OptimizationInstance& opt,
    const FppProjectedLlbiOptions& options,
    const std::vector<double>& y_values_by_eligible_position,
    const std::vector<double>& eta_values);

void export_fpp_projected_llbi_cuts(
    const std::filesystem::path& output_path,
    const std::vector<FppProjectedLlbiSeparatedCut>& cuts);

}  // namespace firebreak::benders
